# safelist
#branches:
#  only:
#  - master

language: python

matrix:
    include:
#        - python: 3.5
#          env:
#            - TRAVIS_PYTHON_VERSION=3.5
#            - CONDA_PY=35
#            - CONDA_NPY=111
        - python: 3.6
          env:
            - TRAVIS_PYTHON_VERSION=3.6
            - CONDA_PY=36
            - CONDA_NPY=111
            - CREATE_DOCS=1

env:
  global:
    - secure: HJT8kvOUUzMY1tjzweCwyk2qIbW5RfBXkaHY0sUReFQS2xgRl/Iexl/SBQMD8C0ai32/imi3hpA11fk5/B+MZucO4euKm0VFqb5RmU5WSkejjYcp6M6+kOFRcl9rrH6EV+x5wKv10r62GCsCMvowIPDdFoZE6ZHhLCZ6Lmwuiyr1EU6hDddCFkLihHcR+Kn+Y6f7HQptnrjxXfZc6ZsUxttU8K3z+VZUs5RSegfGaUzReJPVYEaFzQ5Hwat1CiFaeZ0lobCPBVsSteA5YFFIkbUMUtDLyxGwM5W0j0EDm30WF/sLFvDaHjZeb4A2vrEwkyWaRMqfRrpRBLghsjaa6/0PKWk584ZnndY0Hxv26CDfyan1JOo1SA9pfEQ3lay4aXwLbWVYU5SCsPv7Z1oJSKGmKpqRMgDl6oqCCbFn+t4mAwJchnDMevShITrEpFhabjgUUq7HP1h7ghtafuJW0dUmUicsKdXeRWUnhrZKQVV1ZLGGEnbcnglwaq32nZ8MN/BeR38oal+jQjM5Lsxati4wQErbxl4Y+WCjEu3Yq4uqSgC0iGtv/uFYefDcFJhzQL+s7YmuFenor9BAgmiypPoTMarfekGihJZnQBuQUl0dhqwVnFBg70x3eX0G6IuWDRkP9Rj1xNx6f7lREAjxQRAio1+gmp48qPRySwAWXkM=
    - secure: Gov/LAjiBof13l4LFsnExWJS8eFWcgflpQ3V9Ilh5ikSHKCErEnTb/qUbrwT/wCam+9taRAFRm6O5wch5lf8Oz3XkxrfJ6N797kps3Xs5NLxKs7gO9lUqH10OVN0imBEZNPqIxR9G2Tmw8yx7ombZkTvOfredhrPcb88cLxKiVBsyPOlEpAKqDSA91jMZC9jaarrVCGtWnIZFnczBkuNKLf+TQgWSvkE3C9pQsgeryxw0i9eM1aPQGfkGU7FYk6VAUJg5Rpbg5I2dA1rLGbCIUE5uBjWzhH64KBAX+QMQ6BjgfK9gd6LU8lf3ObwKeVdkimqnVqHyASRb+lfTxXk8/JkUUZoxZ6V4VydplCVwGqZiX25IaumH2G9cy3JHBi73FztMxb+EVYFLXmtZUG11G+6h3YIoT5Rd4xvmjgxwIVCdtHNghQ2XxBk1IkItqSRHnpo9G2ZKXV7lDBA3K+ZmPHX4nQSmhs5wtSX7fEImzW6rTyWoKMsKQWNStovotgu+sD38PXjaNDxfUh3BqKOUj38QozvE3i0xNz5KUoqfvBAjogKHaIsbLhD+bi0hFaR7RY1JKrJhw4mXuO0lA/CS2/4aKhwz3xL6U9CXkDrLiB6DsDpRCNVXwTP4wMcYIHz4n1AU6vUmjrmiZFGOvOcT0EfvPB0gXIaWOARW8wgqYA=

install:
  - 'echo [pypi] > ~/.pypirc'
  - 'echo "username: MaxBo" >> ~/.pypirc'
  - 'echo "password: $PYPIPASSWORD" >> ~/.pypirc'
  - 'cat ~/.pypirc'

  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install conda-build=2.1
  - conda install anaconda-client
  # Useful for debugging any issues with conda
  - conda info -a

  - conda config --set show_channel_urls true
  - conda config --remove channels defaults
  - conda config --add channels defaults
  - conda config --add channels conda-forge
  - conda config --add channels MaxBo

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - export TMPDIR=`dirname $(mktemp -u -t tmp.XXXXXXXXXX)`

  - conda install -y sphinx numpydoc
  - pip install --user travis-sphinx

script:
  # Your test script goes here
  - conda info -a
  - conda build wiver/conda.recipe --user MaxBo --token $ANACONDA_TOKEN

  # build documentation
  - if [ "${CREATE_DOCS}" = "1" ]; then
      conda install -y --use-local wiver;
      sphinx-apidoc -f --separate -o docs_rst/wiver wiver/src/wiver;
      travis-sphinx --source docs_rst --nowarn build;
    fi

after_success:
  - if [ "${CREATE_DOCS}" = "1" ]; then travis-sphinx deploy; fi
  - if [ "${TRAVIS_TAG}" ]; then
      conda install -y cythonarrays twine;
      cd $TRAVIS_BUILD_DIR/wiver;
      python setup.py sdist;
      twine upload --skip-existing dist/*;
    fi
