{% set data = load_setup_py_data() %}

package:
  name: wiver
  version: {{ data.get('version') }}

source:
  path: ../

build:
  number: 0
  script_env:
   - TMPDIR

requirements:
  build:
    - python
    - orca
    - cythonarrays
    - matrixconverters
    - openpyxl

  run:
    - python
    - orca
    - cythonarrays
    - matrixconverters
    - openpyxl
    - pytest-benchmark

test:
  requires:
    - pytest-benchmark

  commands:
    - py.test --junitxml={{ environ["TMPDIR"] }}/junit_test_results.xml --pyargs wiver

about:
  home: https://maxbo.github.io/wiver
  license: GPL2
summary: 'commercial trip model..'
