{% set data = load_setup_py_data() %}

package:
  name: wiver
  version: {{ data.get('version') }}

source:
  path: ../

build:
  number: 0
  script_env:
   - TMPDIR

requirements:
  host:
    - python
    - pip
    - cythoninstallhelpers
    - cythonarrays

  build:
    - python
    - setuptools
    - cython
    - numpy
    - xarray
    - pandas
    - pytables
    - orca
    - cythoninstallhelpers
    - cythonarrays
    - matrixconverters
    - openpyxl
    - pytest=3
    - pytest-runner
    - pytest-benchmark

  run:
    - python
    - setuptools
    - numpy
    - xarray
    - pandas
    - orca
    - cythoninstallhelpers
    - cythonarrays
    - matrixconverters
    - openpyxl

test:
  requires:
    - pytest=3
    - pytest-runner
    - pytest-benchmark

  commands:
    - py.test --junitxml={{ environ["TMPDIR"] }}/junit_test_results.xml --pyargs wiver

about:
  home: https://maxbo.github.io/wiver
  license: GPL2
summary: 'commercial trip model..'
