{% set data = load_setup_py_data() %}

package:
  name: wiver
  version: {{ data.get('version') }}

source:
  path: ../

build:
  number: 0
  script_env:
   - TMPDIR

requirements:
  build:
    - python
    - orca
    - cythonarrays
    - matrixconverters
    - openpyxl
    - h5netcdf

  run:
    - python
    - orca
    - cythonarrays
    - matrixconverters
    - openpyxl
    - pytest-benchmark
    - pytest-cov
    - h5netcdf

test:
  requires:
    - pytest-benchmark
    - pytest-cov

  commands:
    - py.test --pyargs wiver

about:
  home: https://maxbo.github.io/wiver
  license: GPL2
summary: 'commercial trip model..'
