{% set version_str = load_file_regex(load_file='src/wiver/_version.py', regex_pattern='^[_]{0,2}version[_]{0,2}\\s*=\\s*[\'\\"]([^\'\\"]*)[\'\\"]') %}

package:
  name: wiver
  version: {{ version_str[1] }}

source:
  path: ../

build:
  number: 0
  script_env:
   - TMPDIR

requirements:
  build:
    - python
    - setuptools>=61.0
    - cythonarrays

  run:
    - python
    - orca
    - cythonarrays
    - matrixconverters
    - openpyxl
    - h5netcdf
    - xarray

test:
  requires:
    - pytest-benchmark
    - pytest-cov

  commands:
    - py.test --pyargs wiver

about:
  home: https://maxbo.github.io/wiver
  license: GPL2
summary: 'commercial trip model..'
