name: build conda for Linux

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, '3.10']
    steps:
    - uses: actions/checkout@v2
    - name: Setup base conda for Python 3.7
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: 3.7
        conda-channels: MaxBo, conda-forge, defaults

    - name: Install dependencies and set channels
      run: |
        conda install conda-build conda-verify anaconda-client twine readme_renderer
        conda info -a
        conda create -q -n test-environment python=${{ matrix.python-version }} pytest-cov

    - name: Build and test wiver
      run: |
        export TMPDIR=${{ runner.TEMP }}
        export CONDA_BLD_PATH=$TMPDIR
        conda install -c maxbo cythonarrays matrixconverters
        conda build --python ${{ matrix.python-version }} wiver/conda.recipe

    - name: Create Docs
      if: ${{ matrix.python-version == '3.10' }}
      run: |
        source activate test-environment
        export PATH=$HOME/.local/bin:$PATH
        conda install -y cythoninstallhelpers cythonarrays matrixconverters
        python -m pip install sphinx sphinxcontrib-napoleon sphinx-autodoc-typehints 'mistune<2' m2r2
        sphinx-apidoc -f --separate -o docs_rst/wiver wiver/src/wiver
        sphinx-build docs_rst ../docs

    - name: Deploy Docs to gh-pages
      if: ${{ matrix.python-version == '3.10' }}
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: ../docs # The folder the action should deploy.

    - name: Upload pyckage to conda
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_GITHUBACTION_TOKEN }}
        ANACONDA_USERNAME: MaxBo

        CONDA_BLD_PATH: ${{ runner.TEMP }}

      #if: ${{ github.ref_type == 'TAG' }}
      run: |
        source activate test-environment
        export PATH=$HOME/.local/bin:$PATH
        anaconda -t $ANACONDA_TOKEN upload --skip-existing --user $ANACONDA_USERNAME $CONDA_BLD_PATH/linux-64/wiver-*.tar.bz2
